# Change these first
owner: speedrapide10 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portfolio
    url: https://speedrapide10.github.io
  - name: Proxmox
    check: "tcp-ping"
    url: pve.speednight.tk
    icon: https://user-images.githubusercontent.com/85310475/210180462-9490f8f5-cc71-43b7-be01-f93c1bfadb07.png
  - name: Proxmox2
    check: "tcp-ping"
    url: pve.speednight.tk
    icon: https://user-images.githubusercontent.com/85310475/210180913-e4f38969-09fc-40a1-89e1-b1057b83fe83.png
  - name: Portainer
    check: "tcp-ping"
    url: portainer.speednight.tk
    icon: https://user-images.githubusercontent.com/85310475/210180914-9b56836e-d27c-4779-a83e-64308b5ab4c8.png
#    port: 53
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration